// Autogenerated from Pigeon (v11.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, WxSceneType) {
  WxSceneTypeFriend = 0,
  WxSceneTypeTimeLine = 1,
};

/// Wrapper for WxSceneType to allow for nullability.
@interface WxSceneTypeBox : NSObject
@property(nonatomic, assign) WxSceneType value;
- (instancetype)initWithValue:(WxSceneType)value;
@end

@class WxShareBaseModel;
@class WxSdkOnResp;
@class WxShareWebPage;
@class WxShareImage;

@interface WxShareBaseModel : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTitle:(NSString *)title
    content:(NSString *)content
    scene:(WxSceneType)scene
    thumbImageUrl:(NSString *)thumbImageUrl;
@property(nonatomic, copy) NSString * title;
@property(nonatomic, copy) NSString * content;
@property(nonatomic, assign) WxSceneType scene;
@property(nonatomic, copy) NSString * thumbImageUrl;
@end

@interface WxSdkOnResp : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithErrCode:(NSNumber *)errCode
    type:(NSNumber *)type
    country:(nullable NSString *)country
    lang:(nullable NSString *)lang
    errorDescription:(nullable NSString *)errorDescription;
@property(nonatomic, strong) NSNumber * errCode;
@property(nonatomic, strong) NSNumber * type;
@property(nonatomic, copy, nullable) NSString * country;
@property(nonatomic, copy, nullable) NSString * lang;
@property(nonatomic, copy, nullable) NSString * errorDescription;
@end

@interface WxShareWebPage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithPageUrl:(NSString *)pageUrl
    base:(WxShareBaseModel *)base;
@property(nonatomic, copy) NSString * pageUrl;
@property(nonatomic, strong) WxShareBaseModel * base;
@end

@interface WxShareImage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithImageData:(nullable FlutterStandardTypedData *)imageData
    base:(WxShareBaseModel *)base;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * imageData;
@property(nonatomic, strong) WxShareBaseModel * base;
@end

/// The codec used by WeChatOpenSdkApi.
NSObject<FlutterMessageCodec> *WeChatOpenSdkApiGetCodec(void);

@protocol WeChatOpenSdkApi
- (void)registerAppAppId:(NSString *)appId urlSchema:(NSString *)urlSchema universalLink:(NSString *)universalLink completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)isWxInstalledWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)shareWebPageReq:(WxShareWebPage *)req completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)shareImageReq:(WxShareImage *)req completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)weChatAuthWithCompletion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
@end

extern void WeChatOpenSdkApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WeChatOpenSdkApi> *_Nullable api);

/// The codec used by WxSdkOnRespApi.
NSObject<FlutterMessageCodec> *WxSdkOnRespApiGetCodec(void);

@interface WxSdkOnRespApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onRespResp:(WxSdkOnResp *)resp completion:(void (^)(FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
